### ISSUE TITLE
Export and import of sessions

### ISSUE THREAD

**Issue by chilbes** [uzh-bf/klicker-uzh#2474]
Questions can be exported which is great.

It would be very useful to have an export of sessions as well. This could work like this:

- select sessions for export
- export file with all the questions (#5 ) and the sessions structure (without results) is created
- upon import, system checks whether questions already do exist (avoid duplicates) imports questions in question pool and imports sessions

If we would have session tags (#21 ), I would use those to tag all sessions related to a specific course, then I would like to select all sessions with specific tags and export this. In this way I could export all questions and sessions of an entire course at once.

**Comment by rschlaefli** [comment]
https://klicker-uzh.feedbear.com/boards/feature-requests/posts/export-and-import-of-sessions
